@echo off
setlocal enabledelayedexpansion
:: ============================================================
:: Axiometica AIR — Installation Script  (Windows)
:: ============================================================
:: Version: v1.1.2
::
:: Modes:
::   install.bat            Docker Compose mode (default, recommended)
::   install.bat --docker   Docker Compose mode (explicit)
::   install.bat --local    Local venv + npm mode (advanced)
::   install.bat --help     Show help
:: ============================================================

set VERSION=1.1.2
set MODE=docker
if /i "%~1"=="--local"  set MODE=local
if /i "%~1"=="--docker" set MODE=docker
if /i "%~1"=="--help"   goto :show_help

echo.
echo ================================================================
echo    Axiometica AIR  v%VERSION%  --  Installer  [%MODE% mode]
echo ================================================================
echo.

if /i "%MODE%"=="docker" goto :docker_mode
if /i "%MODE%"=="local"  goto :local_mode
goto :show_help


:: ============================================================
::  DOCKER MODE  (recommended)
:: ============================================================
:docker_mode

echo [Step 1/9]  Checking prerequisites...
echo.

docker --version >nul 2>&1
if errorlevel 1 (
    echo   [ERROR] Docker not found.
    echo.
    echo   Please install Docker Desktop from:
    echo     https://www.docker.com/products/docker-desktop/
    echo.
    echo   After installing, start Docker Desktop and re-run this script.
    pause & exit /b 1
)
for /f "tokens=*" %%v in ('docker --version') do echo   [OK] %%v

docker compose version >nul 2>&1
if errorlevel 1 (
    echo   [ERROR] Docker Compose v2 not found.
    echo   Please update Docker Desktop to version 4.x or later.
    pause & exit /b 1
)
for /f "tokens=*" %%v in ('docker compose version') do echo   [OK] %%v

docker info >nul 2>&1
if errorlevel 1 (
    echo   [ERROR] Docker is not running.
    echo   Please start Docker Desktop and try again.
    pause & exit /b 1
)
echo   [OK] Docker daemon is running

echo.
echo [Step 2/9]  Configuration...
echo.

if exist ".env" (
    echo   [OK] .env already exists -- skipping (delete it to re-run setup)
    goto :build_images
)

echo   No .env file found. Running quick configuration wizard.
echo   Press ENTER to accept defaults shown in brackets.
echo.

:: Generate secure random tokens using PowerShell
for /f "tokens=*" %%t in ('powershell -NoProfile -Command "[System.Convert]::ToHexString([System.Security.Cryptography.RandomNumberGenerator]::GetBytes(32))"') do set JWT_SECRET=%%t
for /f "tokens=*" %%t in ('powershell -NoProfile -Command "[System.Convert]::ToHexString([System.Security.Cryptography.RandomNumberGenerator]::GetBytes(32))"') do set WATCHER_KEY=%%t
for /f "tokens=*" %%t in ('powershell -NoProfile -Command "[System.Convert]::ToHexString([System.Security.Cryptography.RandomNumberGenerator]::GetBytes(16))"') do set PG_PASS=%%t
for /f "tokens=*" %%t in ('powershell -NoProfile -Command "[System.Convert]::ToHexString([System.Security.Cryptography.RandomNumberGenerator]::GetBytes(16))"') do set REDIS_PASS=%%t

echo   LLM API keys are optional but enable AI-powered incident summaries.
echo.
set /p OPENAI_KEY=   OpenAI API key (sk-...) [leave blank to skip]:
set /p ANTHROPIC_KEY=   Anthropic API key (sk-ant-...) [leave blank to skip]:

echo.
set /p FLOWER_PASS=   Flower monitoring password [changeme]:
if "!FLOWER_PASS!"=="" set FLOWER_PASS=changeme

echo.
echo   Writing .env file...

:: Get current date/time for the header comment
for /f "tokens=*" %%d in ('powershell -NoProfile -Command "Get-Date -Format \"yyyy-MM-dd HH:mm UTC\""') do set GEN_DATE=%%d

(
    echo # -- Axiometica AIR  v%VERSION%  --  Environment Configuration --
    echo # Generated by install.bat on %GEN_DATE%
    echo #
    echo # Edit this file to change passwords, API keys, or thresholds.
    echo.
    echo # -- LLM Providers (optional -- enables AI-generated summaries) --
    echo OPENAI_API_KEY=!OPENAI_KEY!
    echo ANTHROPIC_API_KEY=!ANTHROPIC_KEY!
    echo.
    echo # -- Security (auto-generated -- do not share) --
    echo JWT_SECRET=!JWT_SECRET!
    echo JWT_EXPIRY_HOURS=8
    echo WATCHER_API_KEY=!WATCHER_KEY!
    echo ENVIRONMENT=production
    echo.
    echo # -- Database credentials (auto-generated) --
    echo POSTGRES_USER=postgres
    echo POSTGRES_DB=agentic_os
    echo POSTGRES_PASSWORD=!PG_PASS!
    echo.
    echo # -- Redis credentials (auto-generated) --
    echo REDIS_PASSWORD=!REDIS_PASS!
    echo.
    echo # -- Service Credentials --
    echo NEO4J_BOLT_URL=bolt://neo4j:7687
    echo NEO4J_USER=neo4j
    echo NEO4J_PASSWORD=agentic_os_neo4j
    echo.
    echo FLOWER_USER=admin
    echo FLOWER_PASSWORD=!FLOWER_PASS!
    echo.
    echo # -- Sentry error tracking (optional) --
    echo SENTRY_DSN=
    echo.
    echo # -- Platform --
    echo DEBUG=false
    echo LOG_LEVEL=INFO
    echo ALLOWED_ORIGINS=http://localhost:3000,https://localhost
) > .env
echo   [OK] .env created with auto-generated security tokens

:build_images
echo.
echo [Step 3/9]  Building Docker images (this takes 3-5 minutes on first run)...
docker compose build --parallel
if errorlevel 1 ( echo   [ERROR] Docker build failed. & pause & exit /b 1 )
echo   [OK] All images built

echo.
echo [Step 4/9]  Starting services...
docker compose up -d
if errorlevel 1 ( echo   [ERROR] docker compose up failed. & pause & exit /b 1 )
echo   [OK] Services started

echo.
echo [Step 5/9]  Waiting for PostgreSQL...
set /a attempts=0
:pg_wait
set /a attempts+=1
docker compose exec -T postgres pg_isready -U postgres -q >nul 2>&1
if not errorlevel 1 goto :pg_ready
if !attempts! geq 60 (
    echo   [ERROR] PostgreSQL did not start after 60 seconds.
    echo   Check logs with:  docker compose logs postgres
    pause & exit /b 1
)
timeout /t 1 /nobreak >nul
goto :pg_wait
:pg_ready
echo   [OK] PostgreSQL ready ^(took !attempts!s^)

echo.
echo [Step 6/9]  Waiting for backend API...
set /a attempts=0
:api_wait
set /a attempts+=1
curl -sf http://localhost:8000/api/health >nul 2>&1
if not errorlevel 1 goto :api_ready
if !attempts! geq 120 (
    echo   [ERROR] Backend API did not start after 120 seconds.
    echo   Check logs with:  docker compose logs backend
    pause & exit /b 1
)
timeout /t 1 /nobreak >nul
goto :api_wait
:api_ready
echo   [OK] Backend API ready ^(took !attempts!s^)

echo.
echo [Step 7/9]  Applying database migrations...
for /f "delims=" %%f in ('dir /b /on "backend\migrations\versions\*.sql" 2^>nul') do (
    echo   Applying %%f...
    docker compose exec -T postgres psql -U postgres agentic_os ^
      -f /dev/stdin < "backend\migrations\versions\%%f" >nul 2>&1
    echo   [OK] %%f
)
echo   [OK] Migrations applied

echo.
echo [Step 8/9]  Seeding platform data...
docker compose exec -T backend python /app/setup_oob.py
echo   [OK] Platform data seeded

echo.
echo [Step 9/9]  Initialising CMDB graph...
set /a attempts=0
:neo4j_wait
set /a attempts+=1
docker compose exec -T neo4j cypher-shell -u neo4j -p agentic_os_neo4j "RETURN 1;" >nul 2>&1
if not errorlevel 1 goto :neo4j_ready
if !attempts! geq 45 (
    echo   [WARN] Neo4j did not respond after 45s -- CMDB seed skipped
    goto :docker_summary
)
timeout /t 1 /nobreak >nul
goto :neo4j_wait
:neo4j_ready
if exist "backend\scripts\neo4j_seed.cypher" (
    echo   Seeding CMDB service topology graph...
    type backend\scripts\neo4j_seed.cypher | ^
      docker compose exec -T neo4j cypher-shell -u neo4j -p agentic_os_neo4j >nul 2>&1
)
echo   [OK] CMDB graph seeded

goto :docker_summary


:: ============================================================
::  LOCAL MODE  (advanced)
:: ============================================================
:local_mode

echo [Step 1/7]  Checking prerequisites...

python --version >nul 2>&1
if errorlevel 1 (
    echo   [ERROR] Python 3.11+ required.
    echo   Download from: https://www.python.org/downloads/
    pause & exit /b 1
)
for /f "tokens=*" %%v in ('python --version') do echo   [OK] %%v

node --version >nul 2>&1
if errorlevel 1 (
    echo   [ERROR] Node.js 18+ required.
    echo   Download from: https://nodejs.org/
    pause & exit /b 1
)
for /f "tokens=*" %%v in ('node --version') do echo   [OK] Node.js %%v

psql --version >nul 2>&1
if errorlevel 1 (
    echo   [ERROR] PostgreSQL client (psql) required.
    echo   Download from: https://www.postgresql.org/download/
    pause & exit /b 1
)

echo.
echo [Step 2/7]  Python virtual environment...
cd backend
if not exist "venv" (
    python -m venv venv
)
call venv\Scripts\activate.bat
python -m pip install --upgrade pip -q
pip install -r requirements.txt -q
echo   [OK] Backend dependencies installed

if not exist ".env" (
    for /f "tokens=*" %%t in ('powershell -NoProfile -Command "[System.Convert]::ToHexString([System.Security.Cryptography.RandomNumberGenerator]::GetBytes(32))"') do set JWT_SECRET=%%t
    (
        echo DATABASE_URL=postgresql://postgres:agentic_os@localhost:5432/agentic_os
        echo SQL_ECHO=false
        echo REDIS_URL=redis://localhost:6379/0
        echo CELERY_BROKER_URL=redis://localhost:6379/0
        echo CELERY_RESULT_BACKEND=redis://localhost:6379/0
        echo NEO4J_BOLT_URL=bolt://localhost:7687
        echo NEO4J_USER=neo4j
        echo NEO4J_PASSWORD=agentic_os_neo4j
        echo JWT_SECRET=!JWT_SECRET!
        echo OPENAI_API_KEY=
        echo ANTHROPIC_API_KEY=
        echo DEBUG=false
        echo LOG_LEVEL=INFO
    ) > .env
    echo   [OK] backend\.env created
)

echo.
echo [Step 3/7]  Frontend...
cd ..\frontend
npm install
if not exist ".env.local" (
    echo VITE_API_BASE_URL=http://localhost:8000> .env.local
    echo VITE_WS_BASE_URL=ws://localhost:8000>> .env.local
)
cd ..

echo.
echo [Step 4/7]  PostgreSQL database...
psql -U postgres -tc "SELECT 1 FROM pg_database WHERE datname='agentic_os';" 2>nul | findstr /r "^ *1" >nul
if errorlevel 1 (
    psql -U postgres -c "CREATE DATABASE agentic_os OWNER postgres;"
    psql -U postgres -c "ALTER USER postgres WITH PASSWORD 'agentic_os';"
    echo   [OK] Database created
) else (
    echo   [OK] Database already exists
)

echo.
echo [Step 5/7]  Database tables...
cd backend
call venv\Scripts\activate.bat
python -c "from agentic_os.db.database import init_db; init_db()"
echo   [OK] Tables initialised

echo.
echo [Step 6/7]  SQL migrations...
set DB_URL=postgresql://postgres:agentic_os@localhost:5432/agentic_os
for /f "delims=" %%f in ('dir /b /on "migrations\versions\*.sql" 2^>nul') do (
    echo   Applying %%f...
    psql %DB_URL% -f "migrations\versions\%%f" >nul 2>&1 && echo   [OK] %%f || echo   [WARN] %%f may already be applied
)

echo.
echo [Step 7/7]  Platform seed data...
python setup_oob.py
cd ..

goto :local_summary


:: ============================================================
::  Summaries
:: ============================================================
:docker_summary
echo.
echo ================================================================
echo    Installation Complete!
echo ================================================================
echo.
echo   Running services:
docker compose ps --format "table {{.Name}}\t{{.Status}}" 2>nul
echo.
echo   Open in your browser:
echo     Frontend   -^>  http://localhost:3000       (main application)
echo     API Docs   -^>  http://localhost:8000/docs  (API reference)
echo     Task Queue -^>  http://localhost:5555       (Celery monitor)
echo     CMDB Graph -^>  http://localhost:7474       (Neo4j Browser)
echo.
echo   Default login:  admin@platform.local / admin  (change after first login)
echo.
echo   Useful commands:
echo     docker compose logs -f backend
echo     docker compose logs -f celery_worker
echo     docker compose restart celery_worker
echo     docker compose down
echo.
echo   Documentation:  README.md  .  docs\QUICKSTART.md  .  INSTALL.md
echo.
pause
exit /b 0

:local_summary
echo.
echo ================================================================
echo    Installation Complete!  [local mode]
echo ================================================================
echo.
echo   Start in three Command Prompts:
echo.
echo     1. Backend API:
echo        cd backend ^&^& venv\Scripts\activate
echo        uvicorn agentic_os.main:app --reload --port 8000
echo.
echo     2. Agent worker:
echo        cd backend ^&^& venv\Scripts\activate
echo        celery -A agentic_os.tasks.celery_app worker --loglevel=info
echo.
echo     3. Frontend:
echo        cd frontend ^&^& npm run dev
echo.
echo   Open in your browser:  http://localhost:3000
echo.
pause
exit /b 0

:show_help
echo.
echo   Usage:  install.bat [--docker^|--local]
echo.
echo   --docker   Docker Compose mode (default, recommended)
echo              Requires: Docker Desktop 4.x+
echo.
echo   --local    Local venv + npm mode (advanced)
echo              Requires: Python 3.11+, Node.js 18+, PostgreSQL 15+, Redis 7+
echo.
exit /b 0
