# ============================================================
# Axiometica AIR - Windows Install Script (PowerShell 5.1+)
# ============================================================
# Version: v1.2.0
#
# Usage:
#   Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
#   .\install.ps1
# ============================================================

# Stop on terminating errors but allow native commands to fail
# (we check $LASTEXITCODE manually after each docker call)
$ErrorActionPreference = "Stop"

function Ok($msg)   { Write-Host "  [OK] $msg" -ForegroundColor Green  }
function Info($msg) { Write-Host "  [..] $msg" -ForegroundColor Cyan   }
function Warn($msg) { Write-Host "  [!!] $msg" -ForegroundColor Yellow }
function Fail($msg) { Write-Host "  [XX] $msg" -ForegroundColor Red; exit 1 }
function Hdr($msg)  { Write-Host "`n=== $msg"  -ForegroundColor Blue   }

Write-Host ""
Write-Host "================================================================" -ForegroundColor Cyan
Write-Host "    Axiometica AIR  -  Windows Installer (Docker Desktop)"     -ForegroundColor Cyan
Write-Host "================================================================" -ForegroundColor Cyan
Write-Host ""

# ── Step 1: Prerequisites ─────────────────────────────────────
Hdr "Step 1 of 9  -  Checking prerequisites"

if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
    Fail "Docker not found. Install Docker Desktop from https://www.docker.com/products/docker-desktop"
}
Ok "Docker: $(docker --version)"

# Capture output to avoid polluting the screen; check exit code
$null = docker compose version 2>&1
if ($LASTEXITCODE -ne 0) {
    Fail "Docker Compose plugin not found. Update Docker Desktop to a recent version."
}
Ok "Compose: $(docker compose version --short 2>$null)"

# ── Step 2: Generate .env ─────────────────────────────────────
Hdr "Step 2 of 9  -  Generating .env"

if (Test-Path ".env") {
    Warn ".env already exists - keeping existing secrets"
    Ok "Using existing .env"
}
else {
    Info "Generating secure secrets..."

    # Use RNG.Create() + GetBytes() — compatible with .NET Framework 4.x (PS 5.1)
    function New-Secret {
        param([int]$Bytes = 32)
        $arr = [byte[]]::new($Bytes)
        $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
        $rng.GetBytes($arr)
        $rng.Dispose()
        return ($arr | ForEach-Object { $_.ToString("x2") }) -join ""
    }

    $jwtSecret     = New-Secret 32
    $watcherApiKey = New-Secret 32
    $neo4jPassword = "agentic_os_neo4j"
    $pgPassword    = "agentic_os"
    $redisPassword = "localdev"
    $timestamp     = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

    $lines = @(
        "# Axiometica AIR - Environment Configuration",
        "# Generated by install.ps1 on $timestamp",
        "# DO NOT commit this file to git.",
        "",
        "POSTGRES_PASSWORD=$pgPassword",
        "POSTGRES_USER=postgres",
        "POSTGRES_DB=agentic_os",
        "",
        "NEO4J_PASSWORD=$neo4jPassword",
        "",
        "REDIS_PASSWORD=$redisPassword",
        "",
        "JWT_SECRET=$jwtSecret",
        "WATCHER_API_KEY=$watcherApiKey",
        "",
        "OPENAI_API_KEY=",
        "ANTHROPIC_API_KEY=",
        "",
        "ALLOWED_ORIGINS=http://localhost:3000,https://localhost"
    )

    # Write UTF-8 WITHOUT BOM — Docker Compose env parser chokes on the BOM
    # that Out-File -Encoding utf8 produces in PowerShell 5.1
    $utf8NoBom = [System.Text.UTF8Encoding]::new($false)
    $envPath   = [System.IO.Path]::Combine((Get-Location).Path, ".env")
    [System.IO.File]::WriteAllLines($envPath, $lines, $utf8NoBom)

    Ok ".env generated with secure secrets"
}

# ── Step 3: Build images ──────────────────────────────────────
Hdr "Step 3 of 9  -  Building Docker images (first build: 5-15 min)"
Info "Building all services in parallel..."
docker compose build --parallel
if ($LASTEXITCODE -ne 0) { Fail "Docker build failed. Check output above." }
Ok "All images built"

# ── Step 4: Start services ────────────────────────────────────
Hdr "Step 4 of 9  -  Starting services"
docker compose up -d
if ($LASTEXITCODE -ne 0) { Fail "Failed to start services." }
Ok "Services started"

# ── Step 5: Wait for PostgreSQL ───────────────────────────────
Hdr "Step 5 of 9  -  Waiting for PostgreSQL"
$retries = 30
while ($true) {
    $null = docker compose exec -T postgres pg_isready -U postgres -q 2>&1
    if ($LASTEXITCODE -eq 0) { break }
    $retries--
    if ($retries -le 0) { Fail "PostgreSQL did not become ready. Run: docker compose logs postgres" }
    Info "Waiting for PostgreSQL... ($($retries) retries left)"
    Start-Sleep 2
}
Ok "PostgreSQL is ready"

# ── Step 6: Wait for backend ──────────────────────────────────
Hdr "Step 6 of 9  -  Waiting for backend API"
$retries = 30
while ($true) {
    $null = docker compose exec -T backend python -c "import urllib.request; urllib.request.urlopen('http://localhost:8000/api/health')" 2>&1
    if ($LASTEXITCODE -eq 0) { break }
    $retries--
    if ($retries -le 0) { Fail "Backend did not start. Run: docker compose logs backend" }
    Info "Waiting for backend... ($($retries) retries left)"
    Start-Sleep 3
}
Ok "Backend API is ready"

# ── Step 7: Apply migrations ──────────────────────────────────
Hdr "Step 7 of 9  -  Applying SQL migrations"
$migrationCount = 0
$sqlFiles = Get-ChildItem "backend\migrations\versions\*.sql" | Sort-Object Name
foreach ($f in $sqlFiles) {
    Info "  -> $($f.Name)"
    # Read as single string (-Raw) so the full SQL is sent to psql at once,
    # not as individual lines which confuses multi-statement scripts
    $sqlContent = Get-Content $f.FullName -Raw
    $sqlContent | docker compose exec -T postgres psql -U postgres agentic_os 2>&1 | Out-Null
    $migrationCount++
}
Ok "$migrationCount migration(s) applied"

# ── Step 8: Seed platform data ────────────────────────────────
Hdr "Step 8 of 9  -  Seeding platform data"
Info "Running out-of-box setup (runbooks, policies, actions, settings)..."

# Use try/catch because setup_oob.py exits 1 on partial failure,
# which combined with $ErrorActionPreference=Stop would halt the script
try {
    docker compose exec -T backend python /app/setup_oob.py
    if ($LASTEXITCODE -ne 0) {
        Warn "setup_oob.py reported some failures - check output above"
    }
    else {
        Ok "Platform data seeded"
    }
}
catch {
    Warn "setup_oob.py failed to run: $_"
}

# ── Step 9: Health checks + summary ──────────────────────────
Hdr "Step 9 of 9  -  Health checks"
Write-Host ""

# PostgreSQL
$null = docker compose exec -T postgres psql -U postgres -d agentic_os -c "SELECT 1;" 2>&1
if ($LASTEXITCODE -eq 0) { Ok "PostgreSQL" } else { Warn "PostgreSQL - not responding" }

# Backend API
$null = docker compose exec -T backend python -c "import urllib.request; urllib.request.urlopen('http://localhost:8000/api/health')" 2>&1
if ($LASTEXITCODE -eq 0) { Ok "Backend API" } else { Warn "Backend API - not responding" }

# Neo4j — trim whitespace/CRLF from the parsed value
$neo4jPass = (Get-Content ".env" | Where-Object { $_ -match "^NEO4J_PASSWORD=" } | Select-Object -First 1) -replace "^NEO4J_PASSWORD=", "" -replace "\s", ""
$null = docker compose exec -T neo4j cypher-shell -u neo4j -p $neo4jPass "RETURN 1;" 2>&1
if ($LASTEXITCODE -eq 0) { Ok "Neo4j" } else { Warn "Neo4j - not responding (may still be starting)" }

# Watcher registered
$null = docker compose exec -T postgres psql -U postgres -d agentic_os -tc "SELECT COUNT(*) FROM watcher_registrations;" 2>&1
if ($LASTEXITCODE -eq 0) { Ok "Database schema OK" } else { Warn "Database schema - check migrations" }

Write-Host ""
Write-Host "================================================================" -ForegroundColor Green
Write-Host "  Platform is ready!" -ForegroundColor Green
Write-Host "================================================================" -ForegroundColor Green
Write-Host "  Frontend  ->  http://localhost:3000" -ForegroundColor Green
Write-Host "  API       ->  http://localhost:8000" -ForegroundColor Green
Write-Host "  API Docs  ->  http://localhost:8000/docs" -ForegroundColor Green
Write-Host "  Neo4j     ->  http://localhost:7474" -ForegroundColor Green
Write-Host "  Flower    ->  http://localhost:5555" -ForegroundColor Green
Write-Host "================================================================" -ForegroundColor Green
Write-Host "  Logs:   docker compose logs -f backend" -ForegroundColor Cyan
Write-Host "          docker compose logs -f watcher_brain" -ForegroundColor Cyan
Write-Host "  Status: docker compose ps" -ForegroundColor Cyan
Write-Host "================================================================" -ForegroundColor Green
Write-Host ""
