#!/bin/bash
# ═══════════════════════════════════════════════════════════════════════════════
# AgenticPlatform — Google Cloud VM Deployment Script
#
# Usage:
#   chmod +x scripts/deploy-gcp.sh
#   ./scripts/deploy-gcp.sh [GITHUB_USERNAME] [GITHUB_TOKEN]
#
# Arguments (optional):
#   GITHUB_USERNAME  GitHub username for ghcr.io authentication
#   GITHUB_TOKEN     GitHub Personal Access Token (read:packages scope)
#
# Environment variables (alternative to arguments):
#   GITHUB_USERNAME  GitHub username
#   GITHUB_TOKEN     GitHub Personal Access Token
#
# Examples:
#   ./scripts/deploy-gcp.sh                          # Interactive login prompt
#   ./scripts/deploy-gcp.sh myuser ghp_xxxx          # With credentials
#   GITHUB_USERNAME=myuser GITHUB_TOKEN=ghp_xxxx ./scripts/deploy-gcp.sh
# ═══════════════════════════════════════════════════════════════════════════════

set -euo pipefail

# ── colours ──────────────────────────────────────────────────────────────────
GREEN='\033[0;32m'; BLUE='\033[0;34m'; YELLOW='\033[1;33m'
RED='\033[0;31m';   BOLD='\033[1m';    NC='\033[0m'

ok()   { echo -e "${GREEN}  ✓  $*${NC}"; }
info() { echo -e "${BLUE}  ▸  $*${NC}"; }
warn() { echo -e "${YELLOW}  ⚠  $*${NC}"; }
err()  { echo -e "${RED}  ✗  $*${NC}"; exit 1; }
hdr()  { echo -e "\n${BOLD}${BLUE}═══  $*${NC}"; }

# ── parse arguments ───────────────────────────────────────────────────────────
GITHUB_USERNAME="${1:-${GITHUB_USERNAME:-}}"
GITHUB_TOKEN="${2:-${GITHUB_TOKEN:-}}"

# ── auto-detect docker compose command ───────────────────────────────────────
if docker compose version >/dev/null 2>&1; then
  DC="docker compose"
elif command -v docker-compose >/dev/null 2>&1; then
  DC="docker-compose"
else
  err "Neither 'docker compose' nor 'docker-compose' found. Install Docker first."
fi

echo ""
echo -e "${BOLD}╔══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BOLD}║         AgenticPlatform — GCP Deployment Script              ║${NC}"
echo -e "${BOLD}╚══════════════════════════════════════════════════════════════╝${NC}"
echo ""

# ── Step 1: Prerequisites ─────────────────────────────────────────────────────
hdr "Step 1  —  Prerequisites"

command -v docker >/dev/null 2>&1 || err "Docker not found. Run: curl -fsSL https://get.docker.com | sh"
ok "Docker: $(docker --version | cut -d' ' -f3 | tr -d ',')"
ok "Compose: $($DC version --short 2>/dev/null || $DC version | head -1)"

command -v git >/dev/null 2>&1 || err "git not found. Run: sudo apt-get install -y git"
ok "git: $(git --version)"

# ── Step 2: Enable Docker BuildKit ───────────────────────────────────────────
hdr "Step 2  —  Docker BuildKit"
export DOCKER_BUILDKIT=1
grep -q "DOCKER_BUILDKIT" ~/.bashrc 2>/dev/null || echo "export DOCKER_BUILDKIT=1" >> ~/.bashrc
ok "Docker BuildKit enabled"

# ── Step 3: Clone / update repository ────────────────────────────────────────
hdr "Step 3  —  Repository"
REPO_DIR="axiometica-air"
REPO_URL="https://github.com/axiometica/axiometica-air.git"

if [ -d "$REPO_DIR/.git" ]; then
  info "Repository exists — pulling latest changes from main…"
  cd "$REPO_DIR"
  git pull origin main
else
  info "Cloning repository…"
  git clone "$REPO_URL" "$REPO_DIR"
  cd "$REPO_DIR"
fi
ok "Repository ready on branch: $(git rev-parse --abbrev-ref HEAD)"

# ── Step 4: Create .env with generated secrets ────────────────────────────────
hdr "Step 4  —  Environment configuration"

if [ -f .env ]; then
  warn ".env already exists — keeping existing secrets"
  ok "Using existing .env (delete it to regenerate)"
else
  info "Generating secure secrets…"

  _gen_secret() {
    openssl rand -hex 32 2>/dev/null || \
      python3 -c "import secrets; print(secrets.token_hex(32))" 2>/dev/null || \
      date +%s%N | sha256sum | cut -c1-64
  }

  JWT_SECRET=$(_gen_secret)
  WATCHER_API_KEY=$(_gen_secret)
  PG_PASS=$(_gen_secret | cut -c1-16)
  REDIS_PASS=$(_gen_secret | cut -c1-16)

  # Detect GCP public IP for ALLOWED_ORIGINS
  GCP_IP=$(curl -sf --max-time 3 \
    "http://metadata.google.internal/computeMetadata/v1/instance/network-interfaces/0/access-configs/0/external-ip" \
    -H "Metadata-Flavor: Google" 2>/dev/null || echo "")
  if [ -n "$GCP_IP" ]; then
    ORIGINS="http://${GCP_IP},https://${GCP_IP},http://localhost:3000"
    ok "Detected GCP public IP: ${GCP_IP}"
  else
    ORIGINS="http://localhost:3000,https://localhost"
    warn "Could not detect GCP IP — set ALLOWED_ORIGINS in .env after deployment"
  fi

  cat > .env << ENVEOF
# Agentic Platform — Environment Configuration
# Generated by deploy-gcp.sh on $(date -u '+%Y-%m-%d %H:%M UTC')
# Edit this file to change passwords, API keys, or thresholds.

# ── LLM Providers (optional — enables AI-powered incident summaries) ──
OPENAI_API_KEY=
ANTHROPIC_API_KEY=

# ── Security (auto-generated — do not share) ──────────────────────────
JWT_SECRET=${JWT_SECRET}
JWT_EXPIRY_HOURS=8
WATCHER_API_KEY=${WATCHER_API_KEY}
ENVIRONMENT=production

# ── Database (auto-generated) ─────────────────────────────────────────
POSTGRES_USER=postgres
POSTGRES_DB=agentic_os
POSTGRES_PASSWORD=${PG_PASS}

# ── Redis (auto-generated) ────────────────────────────────────────────
REDIS_PASSWORD=${REDIS_PASS}

# ── Neo4j (CMDB graph) ────────────────────────────────────────────────
NEO4J_BOLT_URL=bolt://neo4j:7687
NEO4J_USER=neo4j
NEO4J_PASSWORD=agentic_os_neo4j

# ── Celery Flower task monitor ────────────────────────────────────────
FLOWER_USER=admin
FLOWER_PASSWORD=changeme

# ── Platform ──────────────────────────────────────────────────────────
DEBUG=false
LOG_LEVEL=INFO
ALLOWED_ORIGINS=${ORIGINS}
ENVEOF

  ok ".env created with auto-generated secrets"
fi

# ── Step 5: GitHub Container Registry login ───────────────────────────────────
hdr "Step 5  —  GitHub Container Registry"

if [ -n "$GITHUB_USERNAME" ] && [ -n "$GITHUB_TOKEN" ]; then
  info "Logging in with provided credentials…"
  echo "$GITHUB_TOKEN" | docker login ghcr.io -u "$GITHUB_USERNAME" --password-stdin
  ok "Authenticated to ghcr.io"
else
  info "No credentials provided — using local build (skipping ghcr.io login)"
  warn "If images need to be pulled from ghcr.io, set GITHUB_USERNAME and GITHUB_TOKEN"
fi

# ── Step 6: Build images ──────────────────────────────────────────────────────
hdr "Step 6  —  Building Docker images"
info "Building all service images (first build: 5–10 min)…"
$DC -f docker-compose.yml -f docker-compose.prod.yml build --parallel
ok "All images built"

# ── Step 7: Start services ────────────────────────────────────────────────────
hdr "Step 7  —  Starting services"
info "Starting in production mode (nginx serves the React SPA)…"
$DC -f docker-compose.yml -f docker-compose.prod.yml up -d --scale frontend=0
ok "All services started"

# ── Step 8: Wait for PostgreSQL ───────────────────────────────────────────────
hdr "Step 8  —  Waiting for PostgreSQL"
info "Waiting for the database to accept connections…"
RETRIES=60
until $DC exec -T postgres pg_isready -U postgres -q 2>/dev/null; do
  RETRIES=$((RETRIES - 1))
  [ $RETRIES -le 0 ] && err "PostgreSQL did not start. Run: $DC logs postgres"
  info "  waiting… ($RETRIES retries left)"
  sleep 2
done
ok "PostgreSQL is ready"

# ── Step 9: Wait for backend API ──────────────────────────────────────────────
hdr "Step 9  —  Waiting for backend API"
info "Waiting for the API to become healthy…"
RETRIES=60
until $DC exec -T backend python -c \
  "import urllib.request; urllib.request.urlopen('http://localhost:8000/api/health')" \
  >/dev/null 2>&1; do
  RETRIES=$((RETRIES - 1))
  [ $RETRIES -le 0 ] && err "Backend API did not start. Run: $DC logs backend"
  info "  waiting… ($RETRIES retries left)"
  sleep 3
done
ok "Backend API is ready"

# ── Step 10: Verify schema migrations actually reached head ──────────────────
# Alembic runs automatically on backend startup (see main.py), but a failure
# there is only logged as a warning — it does NOT stop the backend from
# starting and reporting healthy. Confirmed live: a partial migration once
# left tables created but columns missing, with the backend running the
# whole time against a schema it didn't actually have. Check explicitly
# rather than trusting that "backend is healthy" implies "schema is current".
hdr "Step 10  —  Verifying database schema is up to date"
info "Checking Alembic migration state…"
ALEMBIC_STATE=$($DC exec -T backend alembic -c /app/alembic.ini current 2>&1) || true
if echo "$ALEMBIC_STATE" | grep -q "(head)"; then
  ok "Database schema is at head: $(echo "$ALEMBIC_STATE" | grep -oE '^[a-f0-9]+ \(head\)')"
else
  echo "$ALEMBIC_STATE" | sed 's/^/      /'
  err "Database schema is NOT at head — migration failed or is incomplete. Check: $DC logs backend | grep -i alembic"
fi

# ── Step 11: Apply SQL migrations ─────────────────────────────────────────────
hdr "Step 11  —  Applying SQL migrations"
MIGRATION_COUNT=0
for migration_file in $(ls -1 backend/migrations/versions/*.sql 2>/dev/null | sort); do
  info "  → $(basename "$migration_file")"
  $DC exec -T postgres psql -U postgres agentic_os \
    -f /dev/stdin < "$migration_file" 2>&1 \
    | grep -v "^$" | grep -Ev "NOTICE|already exists" | sed 's/^/      /' || true
  MIGRATION_COUNT=$((MIGRATION_COUNT + 1))
done
ok "${MIGRATION_COUNT} migration(s) applied"

# ── Step 12: Seed platform data ───────────────────────────────────────────────
hdr "Step 12  —  Seeding platform data"
info "Running out-of-box setup (runbooks, policies, approved actions, settings)…"
$DC exec -T backend python /app/setup_oob.py 2>&1 \
  | grep -E "INFO|WARN|ERROR|✓|✗|✅|⚠" | sed 's/^/  /' || true
ok "Platform data seeded"

# ── Step 13: Seed Neo4j CMDB ──────────────────────────────────────────────────
hdr "Step 13  —  Seeding Neo4j CMDB"
NEO4J_PASS=$(grep "^NEO4J_PASSWORD=" .env | cut -d= -f2- | tr -d '"' || echo "agentic_os_neo4j")
RETRIES=20
until $DC exec -T neo4j cypher-shell -u neo4j -p "${NEO4J_PASS}" "RETURN 1;" >/dev/null 2>&1; do
  RETRIES=$((RETRIES - 1))
  if [ $RETRIES -le 0 ]; then
    warn "Neo4j did not respond — CMDB seed skipped (run manually later)"
    break
  fi
  info "  waiting for Neo4j… ($RETRIES retries left)"
  sleep 3
done

if [ $RETRIES -gt 0 ] && [ -f "backend/scripts/neo4j_seed.cypher" ]; then
  info "Seeding CMDB service topology graph…"
  $DC exec -T neo4j cypher-shell -u neo4j -p "${NEO4J_PASS}" \
    < backend/scripts/neo4j_seed.cypher 2>&1 | sed 's/^/  /' || true
  ok "CMDB graph seeded"
fi

# ── Step 14: Get public IP ────────────────────────────────────────────────────
hdr "Step 14  —  Access details"
PUBLIC_IP=$(curl -sf --max-time 3 \
  "http://metadata.google.internal/computeMetadata/v1/instance/network-interfaces/0/access-configs/0/external-ip" \
  -H "Metadata-Flavor: Google" 2>/dev/null || hostname -I | awk '{print $1}')

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}${BOLD}╔══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}${BOLD}║              Deployment Complete!                            ║${NC}"
echo -e "${GREEN}${BOLD}╚══════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "  ${BOLD}Platform URL:${NC}"
echo    "    HTTP  → http://${PUBLIC_IP}"
echo    "    HTTPS → https://${PUBLIC_IP}  (accept self-signed cert warning)"
echo    "    API   → https://${PUBLIC_IP}/docs"
echo ""
echo -e "  ${BOLD}Default login:${NC}  admin@platform.local / admin  (change after first login)"
echo ""
echo -e "  ${BOLD}Useful commands:${NC}"
echo    "    $DC logs -f backend        # follow backend logs"
echo    "    $DC logs -f watcher        # follow watcher logs"
echo    "    $DC ps                     # container status"
echo    "    $DC restart backend        # safe restart (DB preserved)"
echo    "    $DC down                   # stop all services"
echo ""
echo -e "  ${BOLD}GCP VM management:${NC}"
echo    "    gcloud compute instances stop  agentic-platform-demo --zone=us-central1-a"
echo    "    gcloud compute instances start agentic-platform-demo --zone=us-central1-a"
echo ""
